### ISSUE TITLE
Penetration problem in test_body_motion.

### ISSUE THREAD

**Issue by fabriceci** [fabriceci/godot-rapier2d#21]
Capsules get stuck

![Screenshot 2023-10-09 at 19 20 00](https://github.com/fabriceci/godot-rapier2d/assets/6397893/c2661f44-4202-44a6-af6a-608c3a8d8474)

Probably related, other shapes also block.

https://github.com/fabriceci/godot-rapier2d/assets/6397893/c244bfde-5bce-4184-9c30-fa76277321c0

**Comment by Ughuuu** [comment]
The second part is related to parry removing points that it considers bad: 

Disabled it here: https://github.com/appsinacup/parry/commit/ab5426d1a218eeaa4f5b08283a43eae5a709b0eb

**Comment by fabriceci** [comment]
The second part has been well corrected by Parry's modification, well done, all that's left is the first part and a jitter (probably the same problem) detailed in my commentary. [#23](https://github.com/fabriceci/godot-rapier2d/pull/23#issuecomment-1757031810)

**Comment by Ughuuu** [comment]
Closing this as its fixed
